/*
 * RuleMgmtPage.java
 *
 * Created on May 27, 2011, 10:12 AM
 */

package etracs2.bp.application;

/**
 *
 * @author  jzamora
 */
public class BPSettingPage extends javax.swing.JPanel {
    
    /** Creates new form RuleMgmtPage */
    public BPSettingPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xActionBar1 = new com.rameses.rcp.control.XActionBar();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        xDataTable1 = new com.rameses.rcp.control.XDataTable();
        jPanel4 = new javax.swing.JPanel();
        xDataTable2 = new com.rameses.rcp.control.XDataTable();
        jPanel5 = new javax.swing.JPanel();
        xDataTable3 = new com.rameses.rcp.control.XDataTable();

        setLayout(new java.awt.BorderLayout());

        xActionBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        xActionBar1.setDepends(new String[] {"selectedItem"});
        xActionBar1.setDynamic(true);
        xActionBar1.setName("formActions");
        add(xActionBar1, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        xDataTable1.setDynamic(true);
        xDataTable1.setHandler("applicationHandler");
        xDataTable1.setImmediate(true);
        xDataTable1.setName("applicationsignatory");
        jPanel3.add(xDataTable1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Application Signatories", jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        xDataTable2.setDynamic(true);
        xDataTable2.setHandler("assessmentHandler");
        xDataTable2.setImmediate(true);
        xDataTable2.setName("assessmentsignatory");
        jPanel4.add(xDataTable2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Assessment Signatories", jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        xDataTable3.setDynamic(true);
        xDataTable3.setHandler("requirementHandler");
        xDataTable3.setImmediate(true);
        xDataTable3.setName("requirement");
        jPanel5.add(xDataTable3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Requirements", jPanel5);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XDataTable xDataTable1;
    private com.rameses.rcp.control.XDataTable xDataTable2;
    private com.rameses.rcp.control.XDataTable xDataTable3;
    // End of variables declaration//GEN-END:variables
    
}
