afinventory  CREATE TABLE `afinventory` (                 
               `objid` varchar(50) NOT NULL,              
               `schemaname` varchar(25) NOT NULL,         
               `schemaversion` varchar(10) NOT NULL,      
               `docstate` varchar(25) NOT NULL,           
               `irafid` varchar(50) NOT NULL,             
               `irafno` varchar(50) NOT NULL,             
               `iraftype` varchar(25) NOT NULL,           
               `afid` varchar(50) NOT NULL,               
               `aftype` varchar(10) NOT NULL,             
               `afunit` varchar(20) NOT NULL,             
               `stubfrom` int(11) NOT NULL,               
               `stubto` int(11) NOT NULL,                 
               `qtyonhand` int(11) NOT NULL,              
               `qtyissued` int(11) NOT NULL,              
               `prefix` varchar(10) default NULL,         
               `suffix` varchar(10) default NULL,         
               `startseries` int(11) NOT NULL,            
               `endseries` int(11) NOT NULL,              
               `issuedfrom` int(11) default NULL,         
               `issuedto` int(11) default NULL,           
               `dtposted` timestamp NULL default NULL,    
               `aflength` int(11) default NULL,           
               `currentstub` int(11) default NULL,        
               `stubprefix` varchar(50) default NULL,     
               `startserialno` varchar(50) default NULL,  
               PRIMARY KEY  (`objid`)                     
             ) ENGINE=MyISAM DEFAULT CHARSET=latin1       
