afinventorycredit  CREATE TABLE `afinventorycredit` (       
                     `objid` varchar(50) NOT NULL,          
                     `schemaname` varchar(50) NOT NULL,     
                     `schemaversion` varchar(10) NOT NULL,  
                     `docstate` varchar(10) default NULL,   
                     `afinventoryid` varchar(50) NOT NULL,  
                     `irafid` varchar(50) NOT NULL,         
                     `iraftype` varchar(25) NOT NULL,       
                     `afid` varchar(50) NOT NULL,           
                     `aftype` varchar(15) NOT NULL,         
                     `afunit` varchar(15) NOT NULL,         
                     `prefix` varchar(20) default NULL,     
                     `suffix` varchar(20) default NULL,     
                     `startseries` int(11) default NULL,    
                     `endseries` int(11) default NULL,      
                     `stubfrom` int(11) default NULL,       
                     `stubto` int(11) default NULL,         
                     `qtyissued` int(11) default NULL,      
                     `irafno` varchar(50) default NULL,     
                     `stubno` varchar(50) default NULL,     
                     `balance` int(11) default NULL,        
                     `aflength` int(11) default NULL,       
                     PRIMARY KEY  (`objid`)                 
                   ) ENGINE=MyISAM DEFAULT CHARSET=latin1   
