CREATE TABLE revenue (                                                                                 
   objid varchar(50) NOT NULL,                                                                          
   docstate varchar(25) NOT NULL,                                                                       
   remittanceid varchar(50) NOT NULL,                                                                   
   remittanceno varchar(20) NOT NULL,                                                                   
   remittancedate datetime NOT NULL,                                                                    
   remittancetimestamp varchar(12) NOT NULL,                                                            
   liquidationid varchar(50) default NULL,                                                              
   liquidationno varchar(20) default NULL,                                                              
   liquidationdate datetime default NULL,                                                               
   liquidationtimestamp varchar(12) default NULL,                                                       
   depositid varchar(50) default NULL,                                                                  
   depositno varchar(20) default NULL,                                                                  
   depositdate datetime default NULL,                                                                   
   deposittimestamp varchar(12) default NULL,                                                           
   collectorid varchar(50) NOT NULL,                                                                    
   collectorname varchar(70) NOT NULL,                                                                  
   collectortitle varchar(30) NOT NULL,                                                                 
   receipttype varchar(50) NOT NULL,                                                                    
   receiptid varchar(50) NOT NULL,                                                                      
   receiptdate datetime NOT NULL,                                                                       
   receiptamount decimal(14,2) NOT NULL,                                                                
   receiptitemid varchar(50) NOT NULL,                                                                  
   afid varchar(10) NOT NULL,                                                                           
   afcontrolid varchar(50) NOT NULL,                                                                    
   stubno varchar(15) default NULL,                                                                     
   serialno varchar(15) default NULL,                                                                   
   payorname varchar(200) default NULL,                                                                 
   payoraddress varchar(150) default NULL,                                                              
   acctid varchar(50) NOT NULL,                                                                         
   acctno varchar(50) NOT NULL,                                                                         
   accttitle varchar(250) NOT NULL,                                                                     
   fundid varchar(50) NOT NULL,                                                                         
   fundname varchar(50) NOT NULL,                                                                       
   ngasid varchar(50) NOT NULL,                                                                         
   sreid varchar(50) NOT NULL,                                                                          
   amount decimal(14,2) default NULL,                                                                   
   voided int(11) NOT NULL,                                                                             
   PRIMARY KEY  (objid),                                                                                
   KEY FK_revenue_liquidation (liquidationid),                                                        
   KEY FK_revenue_remittance (remittanceid),                                                          
   KEY FK_revenue_deposit (depositid),                                                                
   KEY FK_revenue_incomeaccount (acctid),                                                             
   KEY FK_revenue_ngas (ngasid),                                                                      
   KEY FK_revenue_sre (sreid),                                                                        
   KEY FK_revenue_receipt (receiptid),                                                                
   KEY FK_revenue_af (afid),                                                                          
   KEY FK_revenue_afcontrol (afcontrolid),                                                            
   CONSTRAINT FK_revenue_afcontrol FOREIGN KEY (afcontrolid) REFERENCES afcontrol (objid),        
   CONSTRAINT FK_revenue_af FOREIGN KEY (afid) REFERENCES af (objid),                             
   CONSTRAINT FK_revenue_deposit FOREIGN KEY (depositid) REFERENCES deposit (objid),              
   CONSTRAINT FK_revenue_incomeaccount FOREIGN KEY (acctid) REFERENCES incomeaccount (objid),     
   CONSTRAINT FK_revenue_liquidation FOREIGN KEY (liquidationid) REFERENCES liquidation (objid),  
   CONSTRAINT FK_revenue_ngas FOREIGN KEY (ngasid) REFERENCES account (objid),                    
   CONSTRAINT FK_revenue_remittance FOREIGN KEY (remittanceid) REFERENCES remittance (objid),     
   CONSTRAINT FK_revenue_sre FOREIGN KEY (sreid) REFERENCES account (objid)                       
 ) ENGINE=InnoDB DEFAULT CHARSET=latin1   ;