/*
 * LandRPUPage.java
 *
 * Created on June 25, 2011, 1:45 PM
 */

package etracs2.rpt.faas.rpu.land;

import java.math.BigDecimal;

/**
 *
 * @author  jzamora
 */
public class LandRPUPage extends javax.swing.JPanel {
    
    /** Creates new form LandRPUPage */
    public LandRPUPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        formPanel3 = new com.rameses.rcp.util.FormPanel();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        xNumberField3 = new com.rameses.rcp.control.XNumberField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        xCheckBox1 = new com.rameses.rcp.control.XCheckBox();
        xButton1 = new com.rameses.rcp.control.XButton();
        jPanel4 = new javax.swing.JPanel();
        formPanel4 = new com.rameses.rcp.util.FormPanel();
        xNumberField4 = new com.rameses.rcp.control.XNumberField();
        xNumberField5 = new com.rameses.rcp.control.XNumberField();
        xNumberField6 = new com.rameses.rcp.control.XNumberField();
        formPanel5 = new com.rameses.rcp.util.FormPanel();
        xNumberField9 = new com.rameses.rcp.control.XNumberField();
        xNumberField10 = new com.rameses.rcp.control.XNumberField();
        formPanel6 = new com.rameses.rcp.util.FormPanel();
        xButton2 = new com.rameses.rcp.control.XButton();
        xNumberField11 = new com.rameses.rcp.control.XNumberField();
        xDataTable1 = new com.rameses.rcp.control.XDataTable();
        jLabel2 = new javax.swing.JLabel();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        formPanel7 = new com.rameses.rcp.util.FormPanel();
        xNumberField7 = new com.rameses.rcp.control.XNumberField();
        xNumberField13 = new com.rameses.rcp.control.XNumberField();
        xNumberField8 = new com.rameses.rcp.control.XNumberField();
        xNumberField12 = new com.rameses.rcp.control.XNumberField();
        xDataTable2 = new com.rameses.rcp.control.XDataTable();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("General Information");
        formPanel1.setBorder(xTitledBorder1);
        xLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel1.setCaption("Revision Year");
        xLabel1.setName("rpu.info.ry");
        xLabel1.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel1.add(xLabel1);

        xLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel2.setCaption("PIN");
        xLabel2.setName("rpu.info.fullpin");
        xLabel2.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel1.add(xLabel2);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setTitle("Taxability");
        formPanel2.setBorder(xTitledBorder2);
        xComboBox1.setCaption("Taxability");
        xComboBox1.setCaptionWidth(90);
        xComboBox1.setImmediate(true);
        xComboBox1.setItems("taxabilities");
        xComboBox1.setName("rpu.info.taxable");
        xComboBox1.setPreferredSize(new java.awt.Dimension(0, 22));
        xComboBox1.setRequired(true);
        formPanel2.add(xComboBox1);

        xComboBox2.setCaption("Exempt Reason");
        xComboBox2.setCaptionWidth(90);
        xComboBox2.setDepends(new String[] {"rpu.info.taxable"});
        xComboBox2.setExpression("#{exemptcode}");
        xComboBox2.setItems("exemptions");
        xComboBox2.setName("exemption");
        xComboBox2.setPreferredSize(new java.awt.Dimension(0, 22));
        formPanel2.add(xComboBox2);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(formPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 208, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(formPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .add(formPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder3 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder3.setTitle("Assessment Summary");
        formPanel3.setBorder(xTitledBorder3);
        formPanel3.setCaptionBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        formPanel3.setCellpadding(new java.awt.Insets(0, 0, 0, 20));
        formPanel3.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xNumberField1.setEditable(false);
        xNumberField1.setCaption("Base Market Value");
        xNumberField1.setCaptionWidth(110);
        xNumberField1.setCellPadding(new java.awt.Insets(0, 0, 0, 20));
        xNumberField1.setFont(new java.awt.Font("Arial", 1, 12));
        xNumberField1.setName("rpu.info.totalbmv");
        xNumberField1.setPreferredSize(new java.awt.Dimension(130, 19));
        formPanel3.add(xNumberField1);

        xNumberField2.setEditable(false);
        xNumberField2.setCaption("Market Value");
        xNumberField2.setCellPadding(new java.awt.Insets(0, 0, 0, 20));
        xNumberField2.setFont(new java.awt.Font("Arial", 1, 12));
        xNumberField2.setName("rpu.info.totalmv");
        xNumberField2.setPreferredSize(new java.awt.Dimension(130, 19));
        formPanel3.add(xNumberField2);

        xNumberField3.setEditable(false);
        xNumberField3.setCaption("Assessed Value");
        xNumberField3.setCaptionWidth(100);
        xNumberField3.setCellPadding(new java.awt.Insets(0, 0, 0, 20));
        xNumberField3.setFont(new java.awt.Font("Arial", 1, 12));
        xNumberField3.setName("rpu.info.totalav");
        xNumberField3.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel3.add(xNumberField3);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(new com.rameses.rcp.control.border.XUnderlineBorder());
        xCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox1.setText(" Idle Land");
        xCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox1.setName("rpu.info.idleland");
        jPanel3.add(xCheckBox1, java.awt.BorderLayout.CENTER);

        xButton1.setMnemonic('a');
        xButton1.setText("Actual Use Adjustments");
        xButton1.setName("openActualUseAdjustment");
        jPanel3.add(xButton1, java.awt.BorderLayout.EAST);

        xNumberField4.setEditable(false);
        xNumberField4.setCaption("Total Land Area (sq.m.)");
        xNumberField4.setCaptionWidth(135);
        xNumberField4.setFieldType(BigDecimal.class);
        xNumberField4.setFont(new java.awt.Font("Arial", 1, 11));
        xNumberField4.setName("rpu.info.landtotal.areasqm");
        xNumberField4.setPattern("#,##0.000000");
        xNumberField4.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel4.add(xNumberField4);

        xNumberField5.setEditable(false);
        xNumberField5.setCaption("Total Land Area (ha.)");
        xNumberField5.setCaptionWidth(135);
        xNumberField5.setFieldType(BigDecimal.class);
        xNumberField5.setFont(new java.awt.Font("Arial", 1, 11));
        xNumberField5.setName("rpu.info.landtotal.areaha");
        xNumberField5.setPattern("#,##0.000000");
        xNumberField5.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel4.add(xNumberField5);

        xNumberField6.setEditable(false);
        xNumberField6.setCaption("Land Base Market Value");
        xNumberField6.setCaptionWidth(135);
        xNumberField6.setFont(new java.awt.Font("Arial", 1, 11));
        xNumberField6.setName("rpu.info.landtotal.basemarketvalue");
        xNumberField6.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel4.add(xNumberField6);

        xNumberField9.setEditable(false);
        xNumberField9.setCaption("Land Market Value");
        xNumberField9.setCaptionWidth(150);
        xNumberField9.setFont(new java.awt.Font("Arial", 1, 11));
        xNumberField9.setName("rpu.info.landtotal.marketvalue");
        xNumberField9.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel5.add(xNumberField9);

        xNumberField10.setEditable(false);
        xNumberField10.setCaption("Land Assessed Value");
        xNumberField10.setCaptionWidth(150);
        xNumberField10.setFont(new java.awt.Font("Arial", 1, 11));
        xNumberField10.setName("rpu.info.landtotal.assessedvalue");
        xNumberField10.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel5.add(xNumberField10);

        formPanel6.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        formPanel6.setPadding(new java.awt.Insets(0, 0, 0, 0));
        formPanel6.setPreferredSize(new java.awt.Dimension(299, 23));
        formPanel6.setShowCaption(false);
        xButton2.setMnemonic('v');
        xButton2.setText("Land Value Adjustments");
        xButton2.setName("openLandValueAdjustments");
        xButton2.setShowCaption(false);
        formPanel6.add(xButton2);

        xNumberField11.setEditable(false);
        xNumberField11.setCaption("Land Market Value");
        xNumberField11.setCaptionWidth(135);
        xNumberField11.setFont(new java.awt.Font("Arial", 1, 11));
        xNumberField11.setName("rpu.info.landtotal.adjustment");
        xNumberField11.setPreferredSize(new java.awt.Dimension(150, 19));
        xNumberField11.setShowCaption(false);
        formPanel6.add(xNumberField11);

        formPanel5.add(formPanel6);

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 310, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 46, Short.MAX_VALUE)
                .add(formPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 309, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, formPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, formPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setText("Classification * :");

        xComboBox3.setItems("classifications");
        xComboBox3.setName("rpu.info.classcode");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(xComboBox3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(465, Short.MAX_VALUE))
            .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                .addContainerGap())
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(xDataTable1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(xComboBox3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(xDataTable1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jTabbedPane1.addTab("Land Assessment", jPanel2);

        formPanel7.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xNumberField7.setEditable(false);
        xNumberField7.setCaption("Total Base Market Value");
        xNumberField7.setCaptionWidth(135);
        xNumberField7.setFieldType(BigDecimal.class);
        xNumberField7.setFont(new java.awt.Font("Arial", 1, 11));
        xNumberField7.setName("rpu.info.planttotal.basemarketvalue");
        xNumberField7.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel7.add(xNumberField7);

        xNumberField13.setEditable(false);
        xNumberField13.setCaption("Total Adjustment");
        xNumberField13.setCaptionWidth(135);
        xNumberField13.setFieldType(BigDecimal.class);
        xNumberField13.setFont(new java.awt.Font("Arial", 1, 11));
        xNumberField13.setName("rpu.info.planttotal.adjustment");
        xNumberField13.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel7.add(xNumberField13);

        xNumberField8.setEditable(false);
        xNumberField8.setCaption("Total Market Value");
        xNumberField8.setCaptionWidth(135);
        xNumberField8.setFieldType(BigDecimal.class);
        xNumberField8.setFont(new java.awt.Font("Arial", 1, 11));
        xNumberField8.setName("rpu.info.planttotal.marketvalue");
        xNumberField8.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel7.add(xNumberField8);

        xNumberField12.setEditable(false);
        xNumberField12.setCaption("Total Assessed Value");
        xNumberField12.setCaptionWidth(135);
        xNumberField12.setFont(new java.awt.Font("Arial", 1, 11));
        xNumberField12.setName("rpu.info.planttotal.assessedvalue");
        xNumberField12.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel7.add(xNumberField12);

        org.jdesktop.layout.GroupLayout jPanel8Layout = new org.jdesktop.layout.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(365, Short.MAX_VALUE)
                .add(formPanel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 310, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel8Layout.createSequentialGroup()
                .add(formPanel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel6Layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(xDataTable2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                .add(10, 10, 10))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(xDataTable2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jTabbedPane1.addTab("Plants and Trees Assessment", jPanel6);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, formPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(formPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.util.FormPanel formPanel2;
    private com.rameses.rcp.util.FormPanel formPanel3;
    private com.rameses.rcp.util.FormPanel formPanel4;
    private com.rameses.rcp.util.FormPanel formPanel5;
    private com.rameses.rcp.util.FormPanel formPanel6;
    private com.rameses.rcp.util.FormPanel formPanel7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XCheckBox xCheckBox1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XDataTable xDataTable1;
    private com.rameses.rcp.control.XDataTable xDataTable2;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XNumberField xNumberField10;
    private com.rameses.rcp.control.XNumberField xNumberField11;
    private com.rameses.rcp.control.XNumberField xNumberField12;
    private com.rameses.rcp.control.XNumberField xNumberField13;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    private com.rameses.rcp.control.XNumberField xNumberField3;
    private com.rameses.rcp.control.XNumberField xNumberField4;
    private com.rameses.rcp.control.XNumberField xNumberField5;
    private com.rameses.rcp.control.XNumberField xNumberField6;
    private com.rameses.rcp.control.XNumberField xNumberField7;
    private com.rameses.rcp.control.XNumberField xNumberField8;
    private com.rameses.rcp.control.XNumberField xNumberField9;
    // End of variables declaration//GEN-END:variables
    
}
