/*
 * HtmlPage.java
 *
 * Created on August 20, 2011, 4:34 PM
 */

package etracs2.rpt.certification;

/**
 *
 * @author  user
 */
public class HtmlPage extends javax.swing.JPanel {
    
    /**
     * Creates new form HtmlPage
     */
    public HtmlPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xEditorPane1 = new com.rameses.rcp.control.XEditorPane();

        setLayout(new java.awt.BorderLayout());

        xEditorPane1.setFont(new java.awt.Font("Monospaced", 1, 14));
        xEditorPane1.setText("html");
        xEditorPane1.setDepends(new String[] {"selectedItem"});
        xEditorPane1.setName("html");
        add(xEditorPane1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XEditorPane xEditorPane1;
    // End of variables declaration//GEN-END:variables
    
}
