/*
 * RPTCertificationPage.java
 *
 * Created on July 18, 2011, 11:16 AM
 */
package etracs2.rpt.certification;

import com.rameses.rcp.ui.annotations.StyleSheet;

/**
 *
 * @author  rameses
 */
@StyleSheet("etracs2/rpt/certification/CertificationStyle.style")
public class RPTCertificationPage extends javax.swing.JPanel {
    
    /** Creates new form RPTCertificationPage */
    public RPTCertificationPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        jLabel14 = new javax.swing.JLabel();
        xSeparator1 = new com.rameses.rcp.control.XSeparator();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xCheckBox1 = new com.rameses.rcp.control.XCheckBox();
        xTextField6 = new com.rameses.rcp.control.XTextField();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        xActionBar1 = new com.rameses.rcp.control.XActionBar();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        xLabel1.setText("Certification Type :");
        xLabel1.setFont(new java.awt.Font("Dialog", 1, 14));
        jPanel1.add(xLabel1);
        xLabel1.setBounds(10, 10, 150, 21);

        xLabel2.setExpression("#{certification.caption}");
        xLabel2.setFont(new java.awt.Font("Dialog", 1, 14));
        jPanel1.add(xLabel2);
        xLabel2.setBounds(160, 10, 370, 21);

        xPanel1.setLayout(null);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Certifacation Detail");
        xPanel1.setBorder(xTitledBorder1);
        jLabel14.setText("Payment Detail");
        jLabel14.setPreferredSize(new java.awt.Dimension(0, 18));
        xPanel1.add(jLabel14);
        jLabel14.setBounds(12, 256, 92, 19);

        org.jdesktop.layout.GroupLayout xSeparator1Layout = new org.jdesktop.layout.GroupLayout(xSeparator1);
        xSeparator1.setLayout(xSeparator1Layout);
        xSeparator1Layout.setHorizontalGroup(
            xSeparator1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 440, Short.MAX_VALUE)
        );
        xSeparator1Layout.setVerticalGroup(
            xSeparator1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 30, Short.MAX_VALUE)
        );
        xPanel1.add(xSeparator1);
        xSeparator1.setBounds(90, 252, 440, 30);

        xLookupField1.setCaption("Taxpayer");
        xLookupField1.setCaptionWidth(135);
        xLookupField1.setExpression("#{entityname}");
        xLookupField1.setHandler("lookupEntity");
        xLookupField1.setName("taxpayer");
        xLookupField1.setPreferredSize(new java.awt.Dimension(0, 21));
        xLookupField1.setRequired(true);
        formPanel1.add(xLookupField1);

        com.rameses.rcp.control.border.XLineBorder xLineBorder1 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder1.setLineColor(new java.awt.Color(153, 153, 153));
        xLabel3.setBorder(xLineBorder1);
        xLabel3.setCaption("Address");
        xLabel3.setCaptionWidth(135);
        xLabel3.setExpression("#{certification.taxpayeraddress}");
        xLabel3.setPreferredSize(new java.awt.Dimension(0, 21));
        formPanel1.add(xLabel3);

        xTextField2.setCaption("Requested By");
        xTextField2.setCaptionWidth(135);
        xTextField2.setName("certification.requestedby");
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 21));
        xTextField2.setRequired(true);
        formPanel1.add(xTextField2);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 77));
        xTextArea1.setColumns(20);
        xTextArea1.setRows(5);
        xTextArea1.setCaption("Purpose");
        xTextArea1.setCaptionWidth(135);
        xTextArea1.setName("certification.purpose");
        xTextArea1.setPreferredSize(new java.awt.Dimension(120, 60));
        xTextArea1.setRequired(true);
        jScrollPane1.setViewportView(xTextArea1);

        formPanel1.add(jScrollPane1);

        xTextField3.setCaption("<html><u>C</u>ertified By:<font color=\"red\">*</font></html>");
        xTextField3.setCaptionWidth(135);
        xTextField3.setName("certification.certifiedby");
        xTextField3.setPreferredSize(new java.awt.Dimension(0, 21));
        xTextField3.setRequired(true);
        formPanel1.add(xTextField3);

        xTextField4.setCaption("Position/Job Title");
        xTextField4.setCaptionWidth(135);
        xTextField4.setName("certification.certifiedbytitle");
        xTextField4.setPreferredSize(new java.awt.Dimension(0, 21));
        xTextField4.setRequired(true);
        formPanel1.add(xTextField4);

        xTextField5.setCaption("Authority of");
        xTextField5.setCaptionWidth(135);
        xTextField5.setName("certification.byauthority");
        xTextField5.setPreferredSize(new java.awt.Dimension(0, 21));
        formPanel1.add(xTextField5);

        xPanel1.add(formPanel1);
        formPanel1.setBounds(10, 22, 520, 234);

        xCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox1.setText(" is for Official Use?");
        xCheckBox1.setCellPadding(new java.awt.Insets(0, 0, 10, 0));
        xCheckBox1.setFont(new java.awt.Font("Dialog", 1, 12));
        xCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox1.setName("officialuse");
        xCheckBox1.setOpaque(false);
        xCheckBox1.setShowCaption(false);
        formPanel2.add(xCheckBox1);

        xTextField6.setCaption("O.R. No.");
        xTextField6.setCaptionWidth(117);
        xTextField6.setDepends(new String[] {"officialuse"});
        xTextField6.setName("certification.orno");
        xTextField6.setPreferredSize(new java.awt.Dimension(150, 21));
        xTextField6.setRequired(true);
        formPanel2.add(xTextField6);

        xDateField1.setCaption("O.R. Date");
        xDateField1.setCaptionWidth(117);
        xDateField1.setDepends(new String[] {"officialuse"});
        xDateField1.setName("certification.ordate");
        xDateField1.setPreferredSize(new java.awt.Dimension(150, 21));
        xDateField1.setRequired(true);
        formPanel2.add(xDateField1);

        xNumberField1.setCaption("O.R. Amount");
        xNumberField1.setCaptionWidth(117);
        xNumberField1.setDepends(new String[] {"officialuse"});
        xNumberField1.setFieldType(java.math.BigDecimal.class);
        xNumberField1.setName("certification.oramount");
        xNumberField1.setPattern("#, ##0.0");
        xNumberField1.setPreferredSize(new java.awt.Dimension(150, 21));
        xNumberField1.setRequired(true);
        formPanel2.add(xNumberField1);

        xNumberField2.setCaption("Stamp Amount");
        xNumberField2.setCaptionWidth(117);
        xNumberField2.setDepends(new String[] {"officialuse"});
        xNumberField2.setFieldType(java.math.BigDecimal.class);
        xNumberField2.setName("certification.stampamount");
        xNumberField2.setPattern("#, ##0.0");
        xNumberField2.setPreferredSize(new java.awt.Dimension(150, 21));
        xNumberField2.setRequired(true);
        formPanel2.add(xNumberField2);

        xPanel1.add(formPanel2);
        formPanel2.setBounds(30, 280, 500, 134);

        jPanel1.add(xPanel1);
        xPanel1.setBounds(10, 38, 540, 426);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        xActionBar1.setName("formActions");
        add(xActionBar1, java.awt.BorderLayout.NORTH);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.util.FormPanel formPanel2;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XCheckBox xCheckBox1;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XSeparator xSeparator1;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    private com.rameses.rcp.control.XTextField xTextField6;
    // End of variables declaration//GEN-END:variables
    
}
