/*
 * BranchRolePage.java
 *
 * Created on August 4, 2010, 3:56 PM
 */

package user.ui;

import admin.ui.*;

/**
 *
 * @author  rameses
 */
public class UserRolePermissionPage extends javax.swing.JPanel {
    
    /** Creates new form BranchRolePage */
    public UserRolePermissionPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSplitPane1 = new javax.swing.JSplitPane();
        xTable1 = new com.rameses.rcp.control.XTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        xList1 = new com.rameses.rcp.control.XList();

        setLayout(new java.awt.BorderLayout());

        setPreferredSize(new java.awt.Dimension(593, 337));
        jSplitPane1.setDividerLocation(150);
        jSplitPane1.setDividerSize(6);
        xTable1.setDepends(new String[] {"selectedItem"});
        xTable1.setDynamic(true);
        xTable1.setHandler("permissionHandler");
        jSplitPane1.setRightComponent(xTable1);

        jScrollPane1.setName("selectedItem");
        xList1.setItems("permissionGroups");
        xList1.setName("selectedItem");
        jScrollPane1.setViewportView(xList1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private com.rameses.rcp.control.XList xList1;
    private com.rameses.rcp.control.XTable xTable1;
    // End of variables declaration//GEN-END:variables
    
}
