/*
 * BatchCaptureInitPage.java
 *
 * Created on October 22, 2011, 9:32 AM
 */

package etracs2.tc.collection;

/**
 *
 * @author  jzamora
 */
public class BatchCaptureInitPage extends javax.swing.JPanel {
    
    /** Creates new form BatchCaptureInitPage */
    public BatchCaptureInitPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        xDateField2 = new com.rameses.rcp.control.XDateField();
        xButton1 = new com.rameses.rcp.control.XButton();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Collection Information");
        formPanel1.setBorder(xTitledBorder1);
        xComboBox1.setCaption("Collector");
        xComboBox1.setCaptionWidth(110);
        xComboBox1.setExpression("#{name}");
        xComboBox1.setImmediate(true);
        xComboBox1.setItems("collectorlist");
        xComboBox1.setName("collector");
        xComboBox1.setPreferredSize(new java.awt.Dimension(250, 22));
        xComboBox1.setRequired(true);
        formPanel1.add(xComboBox1);

        xComboBox2.setCaption("AF Control");
        xComboBox2.setCaptionWidth(110);
        xComboBox2.setDepends(new String[] {"collector"});
        xComboBox2.setDynamic(true);
        xComboBox2.setExpression("#{afid}:  #{currentseries}: #{endseries}");
        xComboBox2.setImmediate(true);
        xComboBox2.setItems("afcontrollist");
        xComboBox2.setName("afcontrol");
        xComboBox2.setPreferredSize(new java.awt.Dimension(250, 22));
        xComboBox2.setRequired(true);
        formPanel1.add(xComboBox2);

        xComboBox3.setCaption("Collection Type");
        xComboBox3.setCaptionWidth(110);
        xComboBox3.setDepends(new String[] {"afcontrol"});
        xComboBox3.setDynamic(true);
        xComboBox3.setExpression("#{name}");
        xComboBox3.setItems("collectiontypelist");
        xComboBox3.setName("collectiontype");
        xComboBox3.setPreferredSize(new java.awt.Dimension(250, 22));
        xComboBox3.setRequired(true);
        formPanel1.add(xComboBox3);

        xDateField2.setCaption("Default Txn Date");
        xDateField2.setCaptionWidth(110);
        xDateField2.setName("defaulttxndate");
        xDateField2.setPreferredSize(new java.awt.Dimension(120, 19));
        xDateField2.setRequired(true);
        formPanel1.add(xDateField2);

        xButton1.setMnemonic('c');
        xButton1.setText("Create");
        xButton1.setDefaultCommand(true);
        xButton1.setName("createBatch");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(xButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 379, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 147, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(xButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XDateField xDateField2;
    // End of variables declaration//GEN-END:variables
    
}
