/*
 * GeneralCollectionPage.java
 *
 * Created on April 20, 2011, 11:00 AM
 */

package etracs2.tc.collection;

import com.rameses.rcp.ui.annotations.StyleSheet;
import java.math.BigDecimal;

/**
 *
 * @author  jzamora
 */
@StyleSheet("etracs2/tc/collection/CollectionPage.style")
public class LargeCattleTransferCollectionPage extends javax.swing.JPanel {
    
    /** Creates new form GeneralCollectionPage */
    public LargeCattleTransferCollectionPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel3 = new javax.swing.JPanel();
        xLabel9 = new com.rameses.rcp.control.XLabel();
        xActionBar1 = new com.rameses.rcp.control.XActionBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        xNumberField3 = new com.rameses.rcp.control.XNumberField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xLabel7 = new com.rameses.rcp.control.XLabel();
        xLabel10 = new com.rameses.rcp.control.XLabel();
        xLabel8 = new com.rameses.rcp.control.XLabel();
        xActionTextField1 = new com.rameses.rcp.control.XActionTextField();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xSubFormPanel1 = new com.rameses.rcp.control.XSubFormPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        formPanel3 = new com.rameses.rcp.util.FormPanel();
        xSeparator2 = new com.rameses.rcp.control.XSeparator();
        formPanel4 = new com.rameses.rcp.util.FormPanel();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        formPanel8 = new com.rameses.rcp.util.FormPanel();
        xTextField11 = new com.rameses.rcp.control.XTextField();
        xTextField12 = new com.rameses.rcp.control.XTextField();
        xNumberField4 = new com.rameses.rcp.control.XNumberField();
        xSeparator3 = new com.rameses.rcp.control.XSeparator();
        formPanel5 = new com.rameses.rcp.util.FormPanel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xNumberField5 = new com.rameses.rcp.control.XNumberField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xSeparator4 = new com.rameses.rcp.control.XSeparator();
        formPanel6 = new com.rameses.rcp.util.FormPanel();
        formPanel7 = new com.rameses.rcp.util.FormPanel();
        xTextField6 = new com.rameses.rcp.control.XTextField();
        xDateField2 = new com.rameses.rcp.control.XDateField();
        formPanel9 = new com.rameses.rcp.util.FormPanel();
        xTextField7 = new com.rameses.rcp.control.XTextField();
        xTextField9 = new com.rameses.rcp.control.XTextField();
        formPanel10 = new com.rameses.rcp.util.FormPanel();
        xTextField8 = new com.rameses.rcp.control.XTextField();
        xTextField10 = new com.rameses.rcp.control.XTextField();

        setLayout(new java.awt.BorderLayout());

        setPreferredSize(new java.awt.Dimension(884, 487));
        jPanel3.setLayout(new java.awt.BorderLayout());

        xLabel9.setBackground(new java.awt.Color(1, 47, 8));
        xLabel9.setForeground(new java.awt.Color(255, 255, 255));
        xLabel9.setFont(new java.awt.Font("Arial", 1, 18));
        xLabel9.setName("collectionTitle");
        xLabel9.setOpaque(true);
        jPanel3.add(xLabel9, java.awt.BorderLayout.SOUTH);

        xActionBar1.setName("formActions");
        jPanel3.add(xActionBar1, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(230, 100));
        jPanel2.setLayout(null);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel3.setText("Amount Due:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(12, 14, 158, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel4.setText("Total Payment:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(12, 92, 206, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Change:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(12, 170, 158, 20);

        xNumberField1.setEditable(false);
        xNumberField1.setFieldType(BigDecimal.class);
        xNumberField1.setFocusable(false);
        xNumberField1.setFont(new java.awt.Font("Tahoma", 1, 24));
        xNumberField1.setIndex(100);
        xNumberField1.setName("entity.info.amount");
        xNumberField1.setOpaque(false);
        xNumberField1.setPattern("#,##0.00");
        xNumberField1.setReadonly(true);
        jPanel2.add(xNumberField1);
        xNumberField1.setBounds(12, 38, 206, 48);

        xNumberField2.setEditable(false);
        xNumberField2.setFieldType(BigDecimal.class);
        xNumberField2.setFocusable(false);
        xNumberField2.setFont(new java.awt.Font("Tahoma", 1, 24));
        xNumberField2.setIndex(100);
        xNumberField2.setName("entity.info.totalpayment");
        xNumberField2.setOpaque(false);
        xNumberField2.setPattern("#,##0.00");
        xNumberField2.setReadonly(true);
        jPanel2.add(xNumberField2);
        xNumberField2.setBounds(12, 116, 206, 48);

        xNumberField3.setEditable(false);
        xNumberField3.setFieldType(BigDecimal.class);
        xNumberField3.setFocusable(false);
        xNumberField3.setFont(new java.awt.Font("Tahoma", 1, 24));
        xNumberField3.setForeground(new java.awt.Color(204, 0, 0));
        xNumberField3.setIndex(100);
        xNumberField3.setName("entity.info.change");
        xNumberField3.setOpaque(false);
        xNumberField3.setPattern("#,##0.00");
        xNumberField3.setReadonly(true);
        jPanel2.add(xNumberField3);
        xNumberField3.setBounds(12, 196, 206, 48);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.EAST);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        formPanel1.setCaptionBorder(null);
        formPanel1.setCaptionFont(new java.awt.Font("Arial", 0, 12));
        formPanel1.setPadding(new java.awt.Insets(8, 8, 8, 8));

        formPanel2.setCaptionBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        formPanel2.setCaptionFont(new java.awt.Font("Arial", 0, 12));
        formPanel2.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        formPanel2.setPadding(new java.awt.Insets(0, 0, 0, 0));
        formPanel2.setPreferredSize(new java.awt.Dimension(0, 22));
        formPanel2.setShowCaption(false);
        xLabel4.setForeground(new java.awt.Color(204, 0, 0));
        xLabel4.setCaption("AF No. ");
        xLabel4.setCaptionWidth(75);
        xLabel4.setFont(new java.awt.Font("Arial", 1, 14));
        xLabel4.setName("entity.info.afid");
        xLabel4.setPreferredSize(new java.awt.Dimension(60, 20));
        formPanel2.add(xLabel4);

        xLabel7.setForeground(new java.awt.Color(204, 0, 0));
        xLabel7.setCaption("Serial No.");
        xLabel7.setCaptionWidth(80);
        xLabel7.setFont(new java.awt.Font("Arial", 1, 14));
        xLabel7.setName("entity.info.serialno");
        xLabel7.setPreferredSize(new java.awt.Dimension(150, 20));
        formPanel2.add(xLabel7);

        xLabel10.setForeground(new java.awt.Color(204, 0, 0));
        xLabel10.setCaption("Stub No.");
        xLabel10.setCaptionWidth(65);
        xLabel10.setFont(new java.awt.Font("Arial", 1, 14));
        xLabel10.setName("entity.info.stubno");
        xLabel10.setPreferredSize(new java.awt.Dimension(100, 20));
        formPanel2.add(xLabel10);

        xLabel8.setForeground(new java.awt.Color(204, 0, 0));
        xLabel8.setCaption("Mode");
        xLabel8.setCaptionWidth(50);
        xLabel8.setFont(new java.awt.Font("Arial", 1, 14));
        xLabel8.setName("entity.info.mode");
        xLabel8.setPreferredSize(new java.awt.Dimension(150, 20));
        formPanel2.add(xLabel8);

        formPanel1.add(formPanel2);

        xActionTextField1.setActionName("lookupEntity");
        xActionTextField1.setCaption("Payor");
        xActionTextField1.setCaptionWidth(75);
        xActionTextField1.setFont(new java.awt.Font("Arial", 0, 12));
        xActionTextField1.setHint("Search Payor");
        xActionTextField1.setIndex(-10);
        xActionTextField1.setName("entity.info.payorname");
        xActionTextField1.setPreferredSize(new java.awt.Dimension(0, 20));
        formPanel1.add(xActionTextField1);

        xTextField1.setCaption("Paid By");
        xTextField1.setCaptionWidth(75);
        xTextField1.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField1.setName("entity.info.paidby");
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField1.setRequired(true);
        formPanel1.add(xTextField1);

        xTextField2.setCaption("Address");
        xTextField2.setCaptionWidth(75);
        xTextField2.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField2.setName("entity.info.paidbyaddress");
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField2.setRequired(true);
        formPanel1.add(xTextField2);

        xDateField1.setCaption("Txn Date ");
        xDateField1.setCaptionWidth(75);
        xDateField1.setDepends(new String[] {"af"});
        xDateField1.setFont(new java.awt.Font("Arial", 0, 12));
        xDateField1.setName("entity.info.txndate");
        xDateField1.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel1.add(xDateField1);

        jPanel5.add(formPanel1, java.awt.BorderLayout.NORTH);

        xSubFormPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        xSubFormPanel1.setHandler("paymentSummary");
        xSubFormPanel1.setPreferredSize(new java.awt.Dimension(40, 120));
        jPanel5.add(xSubFormPanel1, java.awt.BorderLayout.SOUTH);

        jPanel6.setBackground(java.awt.SystemColor.controlHighlight);
        jPanel6.setPreferredSize(new java.awt.Dimension(566, 382));
        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Record of Transfer of Large Cattle");
        jPanel7.setBorder(xTitledBorder1);

        formPanel3.setAddCaptionColon(false);
        formPanel3.setCaption("Record of Ownership");
        formPanel3.setCaptionBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        formPanel3.setCaptionFont(new java.awt.Font("Arial", 1, 11));
        formPanel3.setCaptionForeground(new java.awt.Color(0, 0, 102));
        formPanel3.setPreferredSize(new java.awt.Dimension(600, 354));
        xSeparator2.setCaption("Purchase Information");
        xSeparator2.setCaptionWidth(135);
        xSeparator2.setPreferredSize(new java.awt.Dimension(700, 20));
        xSeparator2.setShowCaption(true);
        org.jdesktop.layout.GroupLayout xSeparator2Layout = new org.jdesktop.layout.GroupLayout(xSeparator2);
        xSeparator2.setLayout(xSeparator2Layout);
        xSeparator2Layout.setHorizontalGroup(
            xSeparator2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 520, Short.MAX_VALUE)
        );
        xSeparator2Layout.setVerticalGroup(
            xSeparator2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 20, Short.MAX_VALUE)
        );
        formPanel3.add(xSeparator2);

        formPanel4.setPadding(new java.awt.Insets(0, 25, 0, 0));
        formPanel4.setPreferredSize(new java.awt.Dimension(680, 65));
        formPanel4.setShowCaption(false);
        xTextField3.setCaption("Purchased By");
        xTextField3.setCaptionWidth(130);
        xTextField3.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField3.setName("entity.purchasedby");
        xTextField3.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField3.setRequired(true);
        formPanel4.add(xTextField3);

        formPanel8.setCellspacing(20);
        formPanel8.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        formPanel8.setPadding(new java.awt.Insets(0, 0, 0, 0));
        formPanel8.setShowCaption(false);
        xTextField11.setCaption("City/Municipality");
        xTextField11.setCaptionWidth(130);
        xTextField11.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField11.setName("entity.citymuni");
        xTextField11.setPreferredSize(new java.awt.Dimension(200, 19));
        xTextField11.setRequired(true);
        formPanel8.add(xTextField11);

        xTextField12.setCaption("Province");
        xTextField12.setCaptionWidth(80);
        xTextField12.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField12.setName("entity.province");
        xTextField12.setPreferredSize(new java.awt.Dimension(200, 19));
        xTextField12.setRequired(true);
        formPanel8.add(xTextField12);

        formPanel4.add(formPanel8);

        xNumberField4.setCaption("Purchase Price");
        xNumberField4.setCaptionWidth(130);
        xNumberField4.setFieldType(BigDecimal.class);
        xNumberField4.setFont(new java.awt.Font("Arial", 0, 12));
        xNumberField4.setName("entity.price");
        xNumberField4.setPattern("#,##0.00");
        xNumberField4.setPreferredSize(new java.awt.Dimension(200, 19));
        xNumberField4.setRequired(true);
        formPanel4.add(xNumberField4);

        formPanel3.add(formPanel4);

        xSeparator3.setCaption("Cattle Information");
        xSeparator3.setCaptionWidth(115);
        xSeparator3.setPreferredSize(new java.awt.Dimension(700, 20));
        xSeparator3.setShowCaption(true);
        org.jdesktop.layout.GroupLayout xSeparator3Layout = new org.jdesktop.layout.GroupLayout(xSeparator3);
        xSeparator3.setLayout(xSeparator3Layout);
        xSeparator3Layout.setHorizontalGroup(
            xSeparator3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 540, Short.MAX_VALUE)
        );
        xSeparator3Layout.setVerticalGroup(
            xSeparator3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 20, Short.MAX_VALUE)
        );
        formPanel3.add(xSeparator3);

        formPanel5.setPadding(new java.awt.Insets(0, 25, 0, 0));
        formPanel5.setPreferredSize(new java.awt.Dimension(700, 90));
        formPanel5.setShowCaption(false);
        xComboBox1.setCaption("Sex of Cattle");
        xComboBox1.setCaptionWidth(130);
        xComboBox1.setFont(new java.awt.Font("Arial", 0, 12));
        xComboBox1.setItems("sexList");
        xComboBox1.setName("entity.sex");
        xComboBox1.setPreferredSize(new java.awt.Dimension(200, 20));
        xComboBox1.setRequired(true);
        formPanel5.add(xComboBox1);

        xNumberField5.setCaption("Age of Cattle (Yrs.)");
        xNumberField5.setCaptionWidth(130);
        xNumberField5.setFieldType(Integer.class);
        xNumberField5.setFont(new java.awt.Font("Arial", 0, 12));
        xNumberField5.setName("entity.age");
        xNumberField5.setPattern("#,##0");
        xNumberField5.setPreferredSize(new java.awt.Dimension(200, 19));
        xNumberField5.setRequired(true);
        formPanel5.add(xNumberField5);

        xTextField4.setCaption("Brand of Municipality");
        xTextField4.setCaptionWidth(130);
        xTextField4.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField4.setName("entity.municipalitybrand");
        xTextField4.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel5.add(xTextField4);

        xTextField5.setCaption("Brand of Owner");
        xTextField5.setCaptionWidth(130);
        xTextField5.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField5.setName("entity.ownerbrand");
        xTextField5.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel5.add(xTextField5);

        formPanel3.add(formPanel5);

        xSeparator4.setCaption("Original Certificate of Ownership Information");
        xSeparator4.setCaptionWidth(265);
        xSeparator4.setPreferredSize(new java.awt.Dimension(700, 20));
        xSeparator4.setShowCaption(true);
        org.jdesktop.layout.GroupLayout xSeparator4Layout = new org.jdesktop.layout.GroupLayout(xSeparator4);
        xSeparator4.setLayout(xSeparator4Layout);
        xSeparator4Layout.setHorizontalGroup(
            xSeparator4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 390, Short.MAX_VALUE)
        );
        xSeparator4Layout.setVerticalGroup(
            xSeparator4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 20, Short.MAX_VALUE)
        );
        formPanel3.add(xSeparator4);

        formPanel6.setPadding(new java.awt.Insets(0, 25, 0, 0));
        formPanel6.setPreferredSize(new java.awt.Dimension(700, 80));
        formPanel6.setShowCaption(false);

        formPanel7.setCellspacing(20);
        formPanel7.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        formPanel7.setPadding(new java.awt.Insets(0, 0, 0, 0));
        formPanel7.setShowCaption(false);
        xTextField6.setCaption("Certificate No.");
        xTextField6.setCaptionWidth(130);
        xTextField6.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField6.setName("entity.certificateno");
        xTextField6.setPreferredSize(new java.awt.Dimension(200, 19));
        xTextField6.setRequired(true);
        formPanel7.add(xTextField6);

        xDateField2.setCaption("Issue Date");
        xDateField2.setFont(new java.awt.Font("Arial", 0, 12));
        xDateField2.setName("entity.issuedate");
        xDateField2.setPreferredSize(new java.awt.Dimension(200, 19));
        xDateField2.setRequired(true);
        formPanel7.add(xDateField2);

        formPanel6.add(formPanel7);

        formPanel9.setCellspacing(20);
        formPanel9.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        formPanel9.setPadding(new java.awt.Insets(0, 0, 0, 0));
        formPanel9.setShowCaption(false);
        xTextField7.setCaption("Issued at City/Muni");
        xTextField7.setCaptionWidth(130);
        xTextField7.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField7.setName("entity.issuedcitymuni");
        xTextField7.setPreferredSize(new java.awt.Dimension(200, 19));
        xTextField7.setRequired(true);
        formPanel9.add(xTextField7);

        xTextField9.setCaption("Province");
        xTextField9.setCaptionWidth(80);
        xTextField9.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField9.setName("entity.issuedprovince");
        xTextField9.setPreferredSize(new java.awt.Dimension(200, 19));
        xTextField9.setRequired(true);
        formPanel9.add(xTextField9);

        formPanel6.add(formPanel9);

        formPanel10.setCellspacing(20);
        formPanel10.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        formPanel10.setPadding(new java.awt.Insets(0, 0, 0, 0));
        formPanel10.setShowCaption(false);
        xTextField8.setCaption("Attested By");
        xTextField8.setCaptionWidth(130);
        xTextField8.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField8.setName("entity.attestedby");
        xTextField8.setPreferredSize(new java.awt.Dimension(200, 19));
        xTextField8.setRequired(true);
        formPanel10.add(xTextField8);

        xTextField10.setCaption("Treasurer");
        xTextField10.setCaptionWidth(80);
        xTextField10.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField10.setName("entity.treasurer");
        xTextField10.setPreferredSize(new java.awt.Dimension(200, 19));
        xTextField10.setRequired(true);
        formPanel10.add(xTextField10);

        formPanel6.add(formPanel10);

        formPanel3.add(formPanel6);

        org.jdesktop.layout.GroupLayout jPanel7Layout = new org.jdesktop.layout.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 665, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .add(formPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 320, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        jPanel5.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(jPanel4, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.util.FormPanel formPanel10;
    private com.rameses.rcp.util.FormPanel formPanel2;
    private com.rameses.rcp.util.FormPanel formPanel3;
    private com.rameses.rcp.util.FormPanel formPanel4;
    private com.rameses.rcp.util.FormPanel formPanel5;
    private com.rameses.rcp.util.FormPanel formPanel6;
    private com.rameses.rcp.util.FormPanel formPanel7;
    private com.rameses.rcp.util.FormPanel formPanel8;
    private com.rameses.rcp.util.FormPanel formPanel9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XActionTextField xActionTextField1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XLabel xLabel10;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel7;
    private com.rameses.rcp.control.XLabel xLabel8;
    private com.rameses.rcp.control.XLabel xLabel9;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    private com.rameses.rcp.control.XNumberField xNumberField3;
    private com.rameses.rcp.control.XNumberField xNumberField4;
    private com.rameses.rcp.control.XNumberField xNumberField5;
    private com.rameses.rcp.control.XSeparator xSeparator2;
    private com.rameses.rcp.control.XSeparator xSeparator3;
    private com.rameses.rcp.control.XSeparator xSeparator4;
    private com.rameses.rcp.control.XSubFormPanel xSubFormPanel1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField10;
    private com.rameses.rcp.control.XTextField xTextField11;
    private com.rameses.rcp.control.XTextField xTextField12;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    private com.rameses.rcp.control.XTextField xTextField6;
    private com.rameses.rcp.control.XTextField xTextField7;
    private com.rameses.rcp.control.XTextField xTextField8;
    private com.rameses.rcp.control.XTextField xTextField9;
    // End of variables declaration//GEN-END:variables
    
}
