/*
 * PostCapturePage.java
 *
 * Created on May 11, 2011, 4:18 PM
 */

package etracs2.tc.collection;

import java.math.BigDecimal;

/**
 *
 * @author  jzamora
 */
public class PostCapturePage extends javax.swing.JPanel {
    
    /** Creates new form PostCapturePage */
    public PostCapturePage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xActionBar1 = new com.rameses.rcp.control.XActionBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        xDataTable1 = new com.rameses.rcp.control.XDataTable();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        xActionBar2 = new com.rameses.rcp.control.XActionBar();
        xSubFormPanel1 = new com.rameses.rcp.control.XSubFormPanel();
        xDataTable2 = new com.rameses.rcp.control.XDataTable();

        setLayout(new java.awt.BorderLayout());

        xActionBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        xActionBar1.setName("mainActions");
        add(xActionBar1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 5, 5));
        jPanel2.setLayout(new java.awt.BorderLayout());

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Summary of Collection");
        jPanel2.setBorder(xTitledBorder1);
        jPanel2.setPreferredSize(new java.awt.Dimension(204, 200));
        xDataTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 10, 5));
        xDataTable1.setHandler("summaryHandler");
        xDataTable1.setImmediate(true);
        xDataTable1.setName("selectedSummary");
        xDataTable1.setPreferredSize(new java.awt.Dimension(300, 80));
        jPanel2.add(xDataTable1, java.awt.BorderLayout.WEST);

        xLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 1));
        xLabel1.setFont(new java.awt.Font("Arial", 1, 11));
        xLabel1.setName("caption");
        xLabel1.setPreferredSize(new java.awt.Dimension(42, 20));
        jPanel2.add(xLabel1, java.awt.BorderLayout.NORTH);

        formPanel1.setCaption("");
        formPanel1.setCaptionBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        formPanel1.setEnabled(false);
        formPanel1.setName("entity.amount");
        formPanel1.setPadding(new java.awt.Insets(3, 5, 0, 0));
        formPanel1.setPreferredSize(new java.awt.Dimension(170, 30));
        xNumberField1.setCaption("Total Collection");
        xNumberField1.setCaptionWidth(90);
        xNumberField1.setFieldType(BigDecimal.class);
        xNumberField1.setFont(new java.awt.Font("Tahoma", 1, 14));
        xNumberField1.setForeground(new java.awt.Color(204, 0, 0));
        xNumberField1.setName("entity.amount");
        xNumberField1.setPattern("#,##0.00");
        xNumberField1.setPreferredSize(new java.awt.Dimension(125, 22));
        xNumberField1.setReadonly(true);
        formPanel1.add(xNumberField1);

        jPanel2.add(formPanel1, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 1, 1));
        jPanel3.setLayout(new java.awt.BorderLayout());

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setTitle("Detail of Collection");
        jPanel3.setBorder(xTitledBorder2);
        jPanel4.setLayout(new java.awt.BorderLayout());

        xActionBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        xActionBar2.setDepends(new String[] {"selectedDetail"});
        xActionBar2.setDynamic(true);
        xActionBar2.setName("detailActions");
        xActionBar2.setPadding(new java.awt.Insets(2, 2, 2, 2));
        xActionBar2.setUseToolBar(false);
        jPanel4.add(xActionBar2, java.awt.BorderLayout.NORTH);

        xSubFormPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xSubFormPanel1.setDepends(new String[] {"selectedDetail"});
        xSubFormPanel1.setDynamic(true);
        xSubFormPanel1.setHandler("opener");
        jPanel4.add(xSubFormPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        xDataTable2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        xDataTable2.setDepends(new String[] {"selectedSummary"});
        xDataTable2.setDynamic(true);
        xDataTable2.setHandler("detailHandler");
        xDataTable2.setImmediate(true);
        xDataTable2.setName("selectedDetail");
        xDataTable2.setPreferredSize(new java.awt.Dimension(300, 80));
        jPanel3.add(xDataTable2, java.awt.BorderLayout.WEST);

        jPanel5.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XActionBar xActionBar2;
    private com.rameses.rcp.control.XDataTable xDataTable1;
    private com.rameses.rcp.control.XDataTable xDataTable2;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XSubFormPanel xSubFormPanel1;
    // End of variables declaration//GEN-END:variables
    
}
