/*
 * HtmlPage.java
 *
 * Created on May 9, 2011, 1:33 PM
 */

package etracs2.tc;

/**
 *
 * @author  jzamora
 */
public class HtmlPage extends javax.swing.JPanel {
    
    /** Creates new form HtmlPage */
    public HtmlPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        xEditorPane1 = new com.rameses.rcp.control.XEditorPane();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setName("html");
        xEditorPane1.setName("html");
        jScrollPane1.setViewportView(xEditorPane1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XEditorPane xEditorPane1;
    // End of variables declaration//GEN-END:variables
    
}
