/*
 * FAASFilterPage.java
 *
 * Created on November 22, 2011, 2:09 PM
 */

package etracs2.rpt.faas;

import com.rameses.rcp.ui.annotations.StyleSheet;

/**
 *
 * @author  jzamora
 */
@StyleSheet("etracs2/rpt/faas/FAASFilterPage.style")
public class FAASFilterPage extends javax.swing.JPanel {
    
    /** Creates new form FAASFilterPage */
    public FAASFilterPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        xList1 = new com.rameses.rcp.control.XList();
        xActionBar1 = new com.rameses.rcp.control.XActionBar();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xComboBox4 = new com.rameses.rcp.control.XComboBox();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();

        setLayout(new java.awt.BorderLayout());

        setPreferredSize(new java.awt.Dimension(548, 368));
        xList1.setDynamic(true);
        xList1.setExpression("#{name}");
        xList1.setItems("filterlist");
        xList1.setName("selectedFilter");
        jScrollPane1.setViewportView(xList1);

        add(jScrollPane1, java.awt.BorderLayout.NORTH);

        xActionBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        xActionBar1.setDepends(new String[] {"selectedFilter"});
        xActionBar1.setName("formActions");
        xActionBar1.setUseToolBar(false);
        add(xActionBar1, java.awt.BorderLayout.SOUTH);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Filter Information");
        formPanel1.setBorder(xTitledBorder1);
        xTextField1.setCaption("Name");
        xTextField1.setCaptionWidth(100);
        xTextField1.setName("filter.name");
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField1.setRequired(true);
        xTextField1.setTextCase(com.rameses.rcp.constant.TextCase.NONE);
        formPanel1.add(xTextField1);

        xComboBox4.setCaption("State");
        xComboBox4.setCaptionWidth(100);
        xComboBox4.setDynamic(true);
        xComboBox4.setItems("statelist");
        xComboBox4.setName("filter.info.docstate");
        xComboBox4.setPreferredSize(new java.awt.Dimension(0, 22));
        formPanel1.add(xComboBox4);

        xComboBox1.setCaption("Barangay");
        xComboBox1.setCaptionWidth(100);
        xComboBox1.setDynamic(true);
        xComboBox1.setExpression("#{name}");
        xComboBox1.setItems("barangaylist");
        xComboBox1.setName("filter.info.barangay");
        xComboBox1.setPreferredSize(new java.awt.Dimension(0, 22));
        formPanel1.add(xComboBox1);

        xComboBox2.setCaption("Classification");
        xComboBox2.setCaptionWidth(100);
        xComboBox2.setDynamic(true);
        xComboBox2.setExpression("#{classname}");
        xComboBox2.setItems("classificationlist");
        xComboBox2.setName("filter.info.classification");
        xComboBox2.setPreferredSize(new java.awt.Dimension(0, 22));
        formPanel1.add(xComboBox2);

        xComboBox3.setCaption("Property Type");
        xComboBox3.setCaptionWidth(100);
        xComboBox3.setDynamic(true);
        xComboBox3.setItems("rputypelist");
        xComboBox3.setName("filter.info.rputype");
        xComboBox3.setPreferredSize(new java.awt.Dimension(0, 22));
        formPanel1.add(xComboBox3);

        xLookupField1.setCaption("Owner");
        xLookupField1.setCaptionWidth(100);
        xLookupField1.setExpression("#{entityname}");
        xLookupField1.setHandler("lookupOwner");
        xLookupField1.setName("filter.info.owner");
        xLookupField1.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel1.add(xLookupField1);

        add(formPanel1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XComboBox xComboBox4;
    private com.rameses.rcp.control.XList xList1;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XTextField xTextField1;
    // End of variables declaration//GEN-END:variables
    
}
