/*
 * MapPage.java
 *
 * Created on April 2, 2012, 11:56 AM
 */

package etracs2.rpt.faas;

/**
 *
 * @author  jzamora
 */
public class MapPage extends javax.swing.JPanel {
    
    /** Creates new form MapPage */
    public MapPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        xEditorPane1 = new com.rameses.rcp.control.XEditorPane();
        jPanel1 = new javax.swing.JPanel();
        xActionBar1 = new com.rameses.rcp.control.XActionBar();
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xSeparator1 = new com.rameses.rcp.control.XSeparator();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xSeparator3 = new com.rameses.rcp.control.XSeparator();
        xCheckBox1 = new com.rameses.rcp.control.XCheckBox();
        xCheckBox2 = new com.rameses.rcp.control.XCheckBox();
        xCheckBox3 = new com.rameses.rcp.control.XCheckBox();
        xSeparator2 = new com.rameses.rcp.control.XSeparator();
        xCheckBox4 = new com.rameses.rcp.control.XCheckBox();
        xCheckBox5 = new com.rameses.rcp.control.XCheckBox();

        setLayout(new java.awt.BorderLayout());

        xEditorPane1.setDepends(new String[] {"mappin", "zoom", "showneighbors", "showsection", "showbarangay", "showroads", "showrivers"});
        xEditorPane1.setName("mapHtml");
        jScrollPane1.setViewportView(xEditorPane1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        xActionBar1.setName("mapActions");
        jPanel1.add(xActionBar1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        formPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        formPanel2.setPreferredSize(new java.awt.Dimension(250, 50));
        xTextField1.setCaption("PIN");
        xTextField1.setCaptionWidth(50);
        xTextField1.setName("mappin");
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel2.add(xTextField1);

        xSeparator1.setPreferredSize(new java.awt.Dimension(0, 20));
        formPanel2.add(xSeparator1);

        xNumberField1.setCaption("Zoom");
        xNumberField1.setCaptionWidth(50);
        xNumberField1.setFieldType(Integer.class);
        xNumberField1.setName("zoom");
        xNumberField1.setPreferredSize(new java.awt.Dimension(50, 19));
        formPanel2.add(xNumberField1);

        xSeparator3.setPreferredSize(new java.awt.Dimension(0, 20));
        formPanel2.add(xSeparator3);

        xCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox1.setText("Neighboring Parcels");
        xCheckBox1.setCaption("");
        xCheckBox1.setCaptionWidth(10);
        xCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox1.setName("showneighbors");
        xCheckBox1.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel2.add(xCheckBox1);

        xCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox2.setText("Whole Section");
        xCheckBox2.setCaption("");
        xCheckBox2.setCaptionWidth(10);
        xCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox2.setName("showsection");
        xCheckBox2.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel2.add(xCheckBox2);

        xCheckBox3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox3.setText("Whole Barangay");
        xCheckBox3.setCaption("");
        xCheckBox3.setCaptionWidth(10);
        xCheckBox3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox3.setName("showbarangay");
        xCheckBox3.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel2.add(xCheckBox3);

        xSeparator2.setPreferredSize(new java.awt.Dimension(0, 20));
        formPanel2.add(xSeparator2);

        xCheckBox4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox4.setText("Roads");
        xCheckBox4.setCaption("");
        xCheckBox4.setCaptionWidth(10);
        xCheckBox4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox4.setName("showroads");
        xCheckBox4.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel2.add(xCheckBox4);

        xCheckBox5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox5.setText("Rivers/Creeks");
        xCheckBox5.setCaption("");
        xCheckBox5.setCaptionWidth(10);
        xCheckBox5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox5.setName("showrivers");
        xCheckBox5.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel2.add(xCheckBox5);

        add(formPanel2, java.awt.BorderLayout.EAST);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XCheckBox xCheckBox1;
    private com.rameses.rcp.control.XCheckBox xCheckBox2;
    private com.rameses.rcp.control.XCheckBox xCheckBox3;
    private com.rameses.rcp.control.XCheckBox xCheckBox4;
    private com.rameses.rcp.control.XCheckBox xCheckBox5;
    private com.rameses.rcp.control.XEditorPane xEditorPane1;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XSeparator xSeparator1;
    private com.rameses.rcp.control.XSeparator xSeparator2;
    private com.rameses.rcp.control.XSeparator xSeparator3;
    private com.rameses.rcp.control.XTextField xTextField1;
    // End of variables declaration//GEN-END:variables
    
}
