/*
 * AccountPage.java
 *
 * Created on February 27, 2011, 12:48 PM
 */

package etracs2.tc.af;

import com.rameses.rcp.ui.annotations.StyleSheet;
import java.awt.FlowLayout;

/**
 *
 * @author  jzamss
 */
@StyleSheet("etracs2/tc/af/IRAFPage.style")
public class IRAFPage extends javax.swing.JPanel {
    
    /** Creates new form AccountPage */
    public IRAFPage() {
        initComponents();
        jPanel11.setLayout( new FlowLayout( FlowLayout.LEFT ) );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        xActionTextField1 = new com.rameses.rcp.control.XActionTextField();
        xDataTable1 = new com.rameses.rcp.control.XDataTable();
        jPanel2 = new javax.swing.JPanel();
        xActionBar1 = new com.rameses.rcp.control.XActionBar();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xLabel10 = new com.rameses.rcp.control.XLabel();
        xLabel9 = new com.rameses.rcp.control.XLabel();
        formPanel3 = new com.rameses.rcp.util.FormPanel();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xLabel6 = new com.rameses.rcp.control.XLabel();
        xLabel8 = new com.rameses.rcp.control.XLabel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        xButton2 = new com.rameses.rcp.control.XButton();
        xButton1 = new com.rameses.rcp.control.XButton();
        jPanel8 = new javax.swing.JPanel();
        xDataTable2 = new com.rameses.rcp.control.XDataTable();
        xDataTable3 = new com.rameses.rcp.control.XDataTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        setPreferredSize(new java.awt.Dimension(806, 459));
        jSplitPane1.setDividerLocation(350);
        jPanel1.setLayout(new java.awt.BorderLayout());

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Listing");
        jPanel1.setBorder(xTitledBorder1);
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 1, 3, 5));
        xActionTextField1.setActionName("search");
        xActionTextField1.setCaptionMnemonic('h');
        xActionTextField1.setHint("Search");
        xActionTextField1.setIndex(-1);
        xActionTextField1.setName("searchText");
        xActionTextField1.setPreferredSize(new java.awt.Dimension(200, 19));
        jPanel3.add(xActionTextField1, java.awt.BorderLayout.WEST);

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        xDataTable1.setHandler("listHandler");
        xDataTable1.setImmediate(true);
        xDataTable1.setName("selectedItem");
        jPanel1.add(xDataTable1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setTitle("Document");
        jPanel2.setBorder(xTitledBorder2);
        xActionBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        xActionBar1.setDepends(new String[] {"selectedItem"});
        xActionBar1.setName("formActions");
        jPanel2.add(xActionBar1, java.awt.BorderLayout.NORTH);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 5, 5));
        jPanel5.setLayout(null);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder3 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder3.setTitle("Invoice of Receipt and Accountable Form  Information");
        jPanel5.setBorder(xTitledBorder3);

        xTextField1.setCaption("IRAF No.");
        xTextField1.setCaptionWidth(85);
        xTextField1.setDepends(new String[] {"selectedItem"});
        xTextField1.setName("entity.txnno");
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField1.setRequired(true);
        formPanel1.add(xTextField1);

        xLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel10.setCaption("IRAF Date");
        xLabel10.setCaptionWidth(85);
        xLabel10.setDepends(new String[] {"selectedItem"});
        xLabel10.setName("entity.info.txndate");
        xLabel10.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel1.add(xLabel10);

        xLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel9.setCaption("Prepared By");
        xLabel9.setCaptionWidth(85);
        xLabel9.setDepends(new String[] {"selectedItem"});
        xLabel9.setName("entity.info.preparedby");
        xLabel9.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel1.add(xLabel9);

        jPanel5.add(formPanel1);
        formPanel1.setBounds(2, 26, 286, 80);

        formPanel3.setIndex(1);
        xLookupField1.setCaption("RIV No.");
        xLookupField1.setCaptionWidth(85);
        xLookupField1.setDepends(new String[] {"selectedItem"});
        xLookupField1.setExpression("#{txnno}");
        xLookupField1.setHandler("lookupRiv");
        xLookupField1.setName("riv");
        xLookupField1.setPreferredSize(new java.awt.Dimension(0, 19));
        xLookupField1.setRequired(true);
        formPanel3.add(xLookupField1);

        xLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel6.setCaption("RIV Date");
        xLabel6.setCaptionWidth(85);
        xLabel6.setDepends(new String[] {"selectedItem"});
        xLabel6.setName("entity.info.rivdate");
        xLabel6.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel3.add(xLabel6);

        xLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel8.setCaption("Requested By");
        xLabel8.setCaptionWidth(85);
        xLabel8.setDepends(new String[] {"selectedItem"});
        xLabel8.setName("entity.info.rivrequestedby");
        xLabel8.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel3.add(xLabel8);

        jPanel5.add(formPanel3);
        formPanel3.setBounds(292, 26, 266, 80);

        xLabel1.setForeground(new java.awt.Color(204, 0, 0));
        xLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel1.setCaption("State");
        xLabel1.setCaptionWidth(100);
        xLabel1.setDepends(new String[] {"selectedItem"});
        xLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        xLabel1.setName("entity.docstate");
        xLabel1.setPreferredSize(new java.awt.Dimension(0, 16));
        jPanel5.add(xLabel1);
        xLabel1.setBounds(310, 4, 240, 22);

        jPanel6.setLayout(new java.awt.BorderLayout());

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder4 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder4.setTitle("Requested Items");
        jPanel6.setBorder(xTitledBorder4);
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 4, 2, 4));
        jPanel7.setOpaque(false);
        jPanel11.setPreferredSize(new java.awt.Dimension(100, 34));
        xButton2.setText("Cancelled Series");
        xButton2.setDepends(new String[] {"receivedItem"});
        xButton2.setName("viewCancelledSeries");
        xButton2.setVisibleWhen("#{entity.docstate == 'APPROVED' && entity.info.rivtype == 'LGU' && receivedItem != null && receivedItem.aftype == 'serial'}");
        jPanel11.add(xButton2);

        xButton1.setText("Add");
        xButton1.setName("add");
        jPanel11.add(xButton1);

        jPanel7.add(jPanel11, java.awt.BorderLayout.SOUTH);

        jPanel8.setLayout(null);

        jPanel8.setOpaque(false);
        xDataTable2.setDepends(new String[] {"selectedItem"});
        xDataTable2.setDynamic(true);
        xDataTable2.setHandler("receivedHandler");
        xDataTable2.setImmediate(true);
        xDataTable2.setName("receivedItem");
        jPanel8.add(xDataTable2);
        xDataTable2.setBounds(0, 130, 550, 110);

        xDataTable3.setDepends(new String[] {"selectedItem"});
        xDataTable3.setDynamic(true);
        xDataTable3.setHandler("requestedHandler");
        xDataTable3.setImmediate(true);
        jPanel8.add(xDataTable3);
        xDataTable3.setBounds(0, 0, 550, 110);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Delivered Item(s)");
        jPanel8.add(jLabel1);
        jLabel1.setBounds(0, 110, 550, 20);

        jPanel7.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel7, java.awt.BorderLayout.CENTER);

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
            .add(jPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 311, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.util.FormPanel formPanel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSplitPane jSplitPane1;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XActionTextField xActionTextField1;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XDataTable xDataTable1;
    private com.rameses.rcp.control.XDataTable xDataTable2;
    private com.rameses.rcp.control.XDataTable xDataTable3;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel10;
    private com.rameses.rcp.control.XLabel xLabel6;
    private com.rameses.rcp.control.XLabel xLabel8;
    private com.rameses.rcp.control.XLabel xLabel9;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XTextField xTextField1;
    // End of variables declaration//GEN-END:variables
    
}
