/*
 * PaymentTypeCash.java
 *
 * Created on April 28, 2011, 10:41 AM
 */

package etracs2.tc.collection.paymenttype;

/**
 *
 * @author  jzamora
 */
public class CashPaymentTypePage extends javax.swing.JPanel {
    
    /** Creates new form PaymentTypeCash */
    public CashPaymentTypePage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xActionBar1 = new com.rameses.rcp.control.XActionBar();

        setPreferredSize(new java.awt.Dimension(401, 166));

        formPanel1.setCaptionBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        formPanel1.setCaptionFont(new java.awt.Font("Arial", 0, 20));
        xNumberField1.setCaption("Cash Tendered");
        xNumberField1.setCaptionWidth(190);
        xNumberField1.setFont(new java.awt.Font("Tahoma", 0, 20));
        xNumberField1.setName("cashTendered");
        xNumberField1.setPreferredSize(new java.awt.Dimension(0, 40));
        xNumberField1.setRequired(true);
        formPanel1.add(xNumberField1);

        xActionBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        xActionBar1.setButtonCaptionOrientation(javax.swing.SwingConstants.LEFT);
        xActionBar1.setName("formActions");
        xActionBar1.setOrientationHAlignment(com.rameses.rcp.constant.UIConstants.RIGHT);
        xActionBar1.setUseToolBar(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(xActionBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(formPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .add(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(23, 23, 23)
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 40, Short.MAX_VALUE)
                .add(xActionBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    // End of variables declaration//GEN-END:variables
    
}
